// Frontend-Demo/vue-demo/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'
</script>

<template>
  <div class="container">
    <img src="./assets/vue.svg" class="logo" alt="Vue logo" />
    <h1>Counter App</h1>
    <HelloWorld />
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 2rem;
}

.logo {
  height: 8em;
  padding: 1em;
  will-change: filter;
  transition: filter 300ms;
}

h1 {
  font-size: 3em;
  line-height: 1.1;
  margin: 0;
}
</style>

// Frontend-Demo/react-demo/src/App.tsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="container">
      <img src={reactLogo} className="logo" alt="React logo" />
      <h1>Counter App</h1>
      <div className="counter-display">{count}</div>
      <div className="button-group">
        <button onClick={() => setCount(count - 1)}>Decrement</button>
        <button onClick={() => setCount(count + 1)}>Increment</button>
      </div>
      <button onClick={() => setCount(0)} className="reset-btn">Reset</button>
    </div>
  )
}

export default App
